language: node_js
node_js:
  - 16

cache:
  npm: false

env:
  NODE_ENV="production"

before_install:
  - chmod +x scripts/*.sh

install:
  - npm ci

script:
  - npm run compile || travis_terminate 1;
  - npm run compile-tests || travis_terminate 1;
  - jest || travis_terminate 1;

deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: master
    condition: ${TRAVIS_COMMIT_MESSAGE} == *"[ci release]"*