language: node_js
node_js:
  - 15

cache:
  npm: false

env:
  NODE_ENV="production"

before_install:
  - npm install -g npm@8.1.2

install:
  - npm install

script:
  - npm run compile
  - npm run compile-tests
  - jest