language: node_js
node_js:
  - 12

cache:
  npm: false

env:
  NODE_ENV="production"

install:
  - npm install -g npm@8.1.2
  - npm ci

script:
  - npm run compile || travis_terminate 1;
  - npm run compile-tests || travis_terminate 1;
  - jest || travis_terminate 1;