language: node_js
node_js:
  - 12

cache:
  npm: false

env:
  NODE_ENV="production"

before_install:
  - npm install -g npm@8.1.2

script:
  - ls -lah
  - ls -lah node_modules
  - npm ci --loglevel verbose
  - ls -lah
  - ls -lah node_modules
  - npm run compile
  - npm run compile-tests
  - jest