language: node_js
node_js:
  - 15

cache:
  npm: false

env:
  NODE_ENV="production"

install:
  - npm install
  - npm install -g webpack-cli

script:
  - npm run compile
  - npm run compile-tests
  - jest